# grab OS image
FROM ubuntu:latest

# Install python
RUN apt-get update -y
RUN apt-get install -y python3.10 python3-pip dos2unix

# set environment variables
ENV PORT 8000

# switch working directory
WORKDIR /app

# move requirements into the image
COPY ./requirements.txt /app/requirements.txt


# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy necessary files
COPY app.py /app
COPY templates/ /app/templates
COPY static/ /app/static
COPY scripts/runApp.sh /app/scripts/runApp.sh
COPY config/flask.ini /app/config/flask.ini

# expose port
EXPOSE $PORT

RUN dos2unix /app/scripts/runApp.sh
RUN chmod +x /app/scripts/runApp.sh

# Run application
CMD ["/bin/bash", "-c", "/app/scripts/runApp.sh"]