#grab python-linux image
FROM python:3.10-alpine

# set environment variables
ENV PORT 8000

#move requirements into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

#copy necessary files
COPY app.py /app
COPY templates/ /app/templates
COPY static/ /app/static
COPY scripts/runApp.sh /app/scripts
COPY config/flask.ini /app/config

# configure the container to run in an executed manner
#ENTRYPOINT [ "bash" ]
EXPOSE $PORT

# parameter for the "ENTRYPOINT" above. Basically makes it run the application.
CMD ["/app/scripts/runApp.sh"]