services:
    quarzlet-store:
        build: ./QuizStore
        ports:
            - "8002:8002"
        links:
            - "quarzlet-take"
            - "quarzlet-make"

    quarzlet-take:
        build: ./QuizTake
        ports:
            - "8000:8000"
        develop:
            watch:
                - action: rebuild
                  path: ./QuizTake
                  target: /app
    quarzlet-auth:
        build: .\QuizAuth
        ports:
            - "8003:8003"
        links:
            - "quarzlet-take"
            - "quarzlet-make"

    quarzlet-make:
        build: ./QuizMake
        ports:
            - "8001:8001"
